N1 = float(input('Qual sua nota: '))
N2 = float(input('Qual sua outra nota: '))
S = (N1+N2)
M = ((N1+N2)/2)
Metro = float(input('Quantos Metros: '))
C = (Metro*100)
MM = (Metro*1000)
x = int(input('Digite um numero para ver sua Tabuada > '))
TT = x
a1 = (x*1)
a2 = (x*2)
a3 = (x*3)
a4 = (x*4)
a5 = (x*5)
a6 = (x*6)
a7 = (x*7)
a8 = (x*8)
a9 = (x*9)
a0 = (x*0)
print('{} x {} = {}'.format(x, 1, x*1))
print('{} x {} = {}'.format( x, 2, x*2))
print('{} x {} = {}'.format(x, 3, x*3))
print('{} x {} = {}'.format( x, 4, x*4))
print('{} x {} = {}'.format(x, 5, x*5))
print('{} x {} = {}'.format( x, 6, x*6))
print('{} x {} = {}'.format(x, 7, x*7))
print('{} x {} = {}'.format( x, 8, x*8))
print('{} x {} = {}'.format(x, 9, x*9))
print('{} x {} = {}'.format( x, 0, x*0))
print ('A soma de suas notas > {}! \nA média de suas notas > {}!'.format((N1+N2), ((N1+N2)/2)))
print ('Em M > {} \nEm C > {:.0f} \nEm MM > {:.0f}'.format(Metro, (Metro*100), (Metro*1000)))


