D = float(input('Quantos em Reais: '))
Dolar = (D/3.27)
A = float(input('Qual a altura: '))
L = float(input('Qual a largura: '))
Soma = (A*L)
T = (Soma/2)
P = float(input('Qual o valor do produto: R$'))
DES = (P*0.95)
Sal = float(input('Qual o seu salario: '))
Aum = (Sal*1.15)
print ('O Seu salario com aumento de 15% é R$:{:.2f}'.format(Aum))
print ('O produto com 5% de desconto é R$:{:.2f}'.format(DES))
print ('Sua parede tem a dimensao de {}x{} e sua area e de {}m². \nVoce gasta {} Litros de tinta para pintar essa parede'.format(A, L, Soma,T))
print ('Você pode comprar ${:.2f} Dolares'.format(Dolar))
